### ISSUE TITLE
p-vrab-o[estimate]

### ISSUE THREAD

**Issue by piotor87** [FINNGEN/kanta_lab_harmonisation_public#27]
in `[LABfi_ALL.usagi.csv]`  `p-vrab-o[estimate]` does not have `estimate` as `ADD_INFO:measurementUnit` leading to a duplicate mapping

**Comment by javier-gracia-tabuenca-tuni** [comment]
here is all these that unit in the name `sourceCode` don't agree with the `ADD_INFO:measurementUnit`

![image](https://github.com/user-attachments/assets/fee8ed1d-ec7b-4352-b3f7-bc14981bc1b5)

I have change 
p-vrab-o[estimate] to now have ADD_INFO:measurementUnit = estimate
erytrosyytit,tilavuusosuus[ratio] to have ADD_INFO:measurementUnit = ratio

the other 2 I leave them as ADD_INFO:measurementUnit = NA, bcs cant see what the unit is

**Comment by piotor87** [comment]
Great. The problem is relevant only when there is another entry that can cause duplicates.
